while True:
    print("Temperature(F): " + input.temperature(TemperatureUnit.FAHRENHEIT))
    if input.temperature(TemperatureUnit.FAHRENHEIT) > 160 : 
        light.set_brightness(100)
        light.set_all(light.rgb(255,0,0))
        pause(300)
        light.clear()
        pause(300)
    elif input.temperature(TemperatureUnit.FAHRENHEIT) > 60 :
        light.set_brightness(10)
        light.set_pixel_color(0, light.rgb(255,165,0))
        pause(300)
        light.clear()
        light.set_pixel_color(1, light.rgb(255,255,0))
        pause(300)
        light.clear()
        light.set_pixel_color(2, light.rgb(50,238,50))
        pause(300)
        light.clear()
        light.set_pixel_color(3, light.rgb(0,255,0))
        pause(300)
        light.clear()
        light.set_pixel_color(4, light.rgb(20,81,230))
        pause(300)
        light.clear()
        light.set_pixel_color(5, light.rgb(0,255,255))
        pause(300)
        light.clear()
        light.set_pixel_color(6, light.rgb(0,0,255))
        pause(300)
        light.clear()
        light.set_pixel_color(7, light.rgb(238,130,238))
        pause(300)
        light.clear()
        light.set_pixel_color(8, light.rgb(255,105,180))
        pause(300)
        light.clear()
        light.set_pixel_color(9, light.rgb(255,0,0))
        pause(300)
        light.clear()
    else:
        light.set_all (light.rgb(0,0,255))
